"use strict";
/* ---------- Kundengeschichten (Design – Spielspaß 2.0, Hebel 10; Architektur § 9.7) ----------
   Drei kurze Kapitel je Kunde, frei ab Vertrauen 2, 3 und 4. Jedes: eine Szene im Ton des Kunden mit kleiner Wendung,
   ein Satz des Seniors (Haltung: Gegenfrage statt Lösung, trocken-warm), eine Frage mit Erklärung und die Quelle der
   fachlichen Aussage. Kurz halten – das ist Erzählung, kein Lehrbuch.
   DATEN.geschichten[kunde] = [{nr, ab, titel, text, senior, frage:{text, optionen, richtig, erklaerung}, quelle}] */
DATEN.geschichten = (() => {
  const K = (nr, titel, text, senior, frage, optionen, richtig, erklaerung, quelle) =>
    ({nr, ab: nr + 1, titel, text, senior, frage: {text: frage, optionen, richtig, erklaerung}, quelle});
  return {
    salon: [
      K(1, "Das Gäste-WLAN",
        "Mira strahlt: „Die Kundinnen fragen dauernd nach WLAN. Ich häng einfach das Passwort vom Kassen-WLAN an den Spiegel, oder?“ Ihre Nichte Lea nickt eifrig. Du schaust auf die Kasse, auf den Drucker – und auf das Kartenterminal daneben.",
        "„Würdest du deinen Kundinnen auch den Schlüssel zur Kasse an den Spiegel hängen?“",
        "Warum gehört Gäste-WLAN in ein eigenes Netz?",
        ["Weil WLAN sonst langsamer wird", "Weil Gäste sonst an Kasse und Drucker herankommen", "Weil ein Router nur ein Passwort speichern kann"], 1,
        "Im selben Netz kann jedes Gerät eines Gastes Kasse, Drucker und Büro-PC erreichen. Ein getrenntes Gastnetz (eigene SSID, eigenes Netz, nur Internet) verhindert das.",
        "BSI IT-Grundschutz-Kompendium, NET.2.1 WLAN-Betrieb"),
      K(2, "Lea will es lernen",
        "Lea sitzt jetzt öfter im Büro und fragt Löcher in den Bauch. Heute hat sie ihrem Laptop „die Adresse vom Drucker gegeben, weil die ja funktioniert“. Seitdem druckt mal der Drucker, mal antwortet der Laptop. Mira lacht: „Sie kommt eben nach mir.“",
        "„Was passiert, wenn zwei Autos dasselbe Kennzeichen haben?“",
        "Welche Geräte bekommen im kleinen Büro besser eine feste Adresse?",
        ["Geräte, die andere finden müssen – Drucker und Kasse", "Alle Laptops, damit es einheitlich ist", "Keine – feste Adressen sind veraltet"], 0,
        "Drucker und Server brauchen eine feste Adresse (oder eine DHCP-Reservierung), damit die anderen sie finden. Laptops holen sich ihre per DHCP – feste Adressen gehören außerhalb des DHCP-Bereichs.",
        "RFC 2131 (DHCP, „manual allocation“) · Network – Lernfassung"),
      K(3, "Die zweite Filiale",
        "Mira eröffnet einen zweiten Salon am anderen Ende der Stadt. „Da muss doch nur ein langes Kabel rüber, dann ist alles ein Netz.“ Drei Kilometer, sagt Google Maps. Lea hat schon nach Kabelrollen gesucht.",
        "„Brauchst du dasselbe Netz – oder nur dieselben Daten?“",
        "Wie verbindet man zwei Standorte sicher?",
        ["Ein 3 km langes Netzwerkkabel", "Beide nehmen dieselbe öffentliche IP-Adresse", "Ein VPN zwischen den beiden Routern über das Internet"], 2,
        "Twisted-Pair-Ethernet reicht nur 100 Meter. Zwei Standorte verbindet man über das Internet mit einem verschlüsselten Tunnel (Site-to-Site-VPN, z. B. IPsec).",
        "IEEE 802.3ab (1000BASE-T, 100 m) · RFC 4301 (IPsec-Architektur)"),
    ],
    baeckerei: [
      K(1, "Vier Uhr morgens",
        "Um vier ruft Kowalski an. „Jeden Morgen dasselbe: Die Öfen gehen an, und die Kasse ist kurz weg. Dann kommt sie wieder. Ist das Ihr Internet?“ Im Hintergrund brummt es. Der Router steht direkt neben dem Sicherungskasten.",
        "„Was braucht der Router, wenn die Öfen anspringen – Ruhe oder Strom?“",
        "Was schützt Router und Switch vor kurzen Stromeinbrüchen?",
        ["Eine USV (unterbrechungsfreie Stromversorgung)", "Ein zweiter DNS-Server", "Ein längeres Netzwerkkabel"], 0,
        "Eine USV überbrückt Spannungseinbrüche und kurze Ausfälle, bis der Strom wieder stabil ist. Gesichert gehört die Konfiguration trotzdem – eine USV hält nicht ewig.",
        "IEC 62040 (Normreihe für unterbrechungsfreie Stromversorgungen)"),
      K(2, "Der Neffe und Kanal 13",
        "Kevin, der Neffe, hat das WLAN „schneller gemacht“: Kanal 13, „da ist nie was los“. Seitdem findet das alte Bestell-Tablet das Netz nicht mehr. Kowalski: „Das Ding hat mein Bruder aus Amerika mitgebracht. Lief immer.“",
        "„Was kann der älteste Gast im Netz – und wer hat ihn gefragt?“",
        "Warum sieht das Tablet ein WLAN auf Kanal 13 nicht?",
        ["Kanal 13 ist nur für 5 GHz gedacht", "Es ist für einen Markt gebaut, in dem nur Kanäle 1–11 genutzt werden", "Auf Kanal 13 ist WLAN immer unverschlüsselt"], 1,
        "Im 2,4-GHz-Band sind in Europa die Kanäle 1–13 üblich, in den USA arbeiten Geräte nach den FCC-Regeln normalerweise nur auf 1–11. Für den US-Markt gebaute Geräte suchen 12 und 13 meist gar nicht ab.",
        "ETSI EN 300 328 (2,4 GHz, Europa) · FCC 47 CFR Part 15 (USA)"),
      K(3, "Vorbestellen im Netz",
        "Kowalski will einen Online-Shop für Vorbestellungen. „Kevin sagt, wir lassen den auf dem Backstuben-PC laufen und machen am Router ein Loch rein. Kostet nix.“ Der Backstuben-PC ist derselbe, auf dem die Buchhaltung liegt.",
        "„Wen lässt du nachts in die Backstube – und durch welche Tür?“",
        "Warum gehört ein Webshop nicht auf den Büro-PC im LAN?",
        ["Eine Portweiterleitung öffnet von außen einen Weg ins interne Netz", "Webseiten laufen nur auf Linux", "Der PC druckt dann langsamer"], 0,
        "Was aus dem Internet erreichbar ist, gehört in eine DMZ oder zu einem Hoster – getrennt vom internen Netz. Eine Weiterleitung auf einen internen PC macht ihn zum Einfallstor.",
        "BSI IT-Grundschutz-Kompendium, NET.1.1 Netzarchitektur und -design"),
    ],
    schreibbuero: [
      K(1, "Das Wartungsbuch",
        "Albers legt dir ein ledergebundenes Buch hin. „Jede Änderung seit 2009. Datum, Gerät, wer, warum.“ Du blätterst – und findest den Grund für die Störung von letzter Woche schneller als in der Doku des Dienstleisters. Albers hebt eine Augenbraue: „Ordnung, junger Mensch.“",
        "„Wann hast du zuletzt aufgeschrieben, was du geändert hast – und wie man es zurücknimmt?“",
        "Was gehört in eine Änderungsnotiz?",
        ["Das Passwort des Routers, damit es nicht verloren geht", "Nur der Name des Technikers", "Was, wo, wann, warum – und wie man es rückgängig macht"], 2,
        "Eine gute Änderungsnotiz beschreibt die Änderung, das System, den Zeitpunkt, den Grund und den Rückweg. Passwörter gehören in einen Passwortmanager, nie ins Protokoll.",
        "ITIL 4, Practice „Change Enablement“"),
      K(2, "Der Spiegel",
        "Albers hat versehentlich die Mandantenliste gelöscht. „Kein Problem“, sagt er ruhig, „der Server hat ja zwei Platten. RAID. Gespiegelt.“ Ihr schaut auf die zweite Platte. Die Liste ist dort auch weg – sauber gespiegelt.",
        "„Wenn du einen Fehler machst – macht der Spiegel ihn mit?“",
        "Warum ersetzt RAID 1 keine Datensicherung?",
        ["Es spiegelt auch Löschungen und Verschlüsselung sofort", "RAID 1 hilft nur bei Stromausfall", "RAID 1 komprimiert die Daten"], 0,
        "RAID schützt vor dem Ausfall einer Platte, nicht vor Löschen, Ransomware oder Brand. Dafür braucht es Sicherungen – zum Beispiel nach der 3-2-1-Regel: drei Kopien, zwei Medien, eine außer Haus.",
        "BSI IT-Grundschutz-Kompendium, CON.3 Datensicherungskonzept"),
      K(3, "Die neue Kollegin",
        "Frau Yilmaz fängt an und braucht Zugriff auf ihren Ordner. Albers: „Geben Sie ihr einfach das Administrator-Kennwort, das haben hier alle. Geht schneller.“ Er meint es freundlich. Du denkst an das Wartungsbuch.",
        "„Wer braucht wirklich den Generalschlüssel – und wer nur den für seine Tür?“",
        "Welches Prinzip gilt für Berechtigungen?",
        ["Alle bekommen dasselbe, damit niemand warten muss", "So wenig wie nötig – jede Person nur, was sie braucht", "Admin für alle, aber das Passwort monatlich wechseln"], 1,
        "Berechtigungen werden nach dem Minimalprinzip vergeben (Need-to-know, Least Privilege). Ein geteiltes Admin-Kennwort macht nicht nachvollziehbar, wer was getan hat.",
        "BSI IT-Grundschutz-Kompendium, ORP.4 Identitäts- und Berechtigungsmanagement"),
    ],
    praxis: [
      K(1, "Das Wartezimmer",
        "Frau Krämer hat Patienten, die nach WLAN fragen, und einen Laptop am Empfang, auf dem Patientenakten liegen. „Früher hing der Gast-Laptop am selben Switch wie der Empfang. Das ist doch jetzt anders, oder?“ Sie schaut dich sehr genau an.",
        "„Woher weiß der Switch, wer zu wem gehört?“",
        "Was trennt Gäste und Praxis am selben Switch?",
        ["Längere Kabel für die Gäste", "Ein zweiter DNS-Server", "VLANs – logisch getrennte Netze"], 2,
        "VLANs teilen einen Switch in getrennte Netze (Broadcast-Domänen). Verkehr dazwischen geht nur über den Router – und dessen Regeln.",
        "IEEE 802.1Q · VLAN – Lernfassung"),
      K(2, "Die Röntgenbilder",
        "Dr. Müller will einem Kollegen Röntgenbilder schicken. „Per Mail, wie immer.“ Frau Krämer verschränkt die Arme: „Nicht ohne Verschlüsselung.“ Beide schauen dich an. Du merkst, dass hier gerade nicht über Technik gestritten wird.",
        "„Würdest du die Bilder auf einer Postkarte verschicken?“",
        "Was gilt für Gesundheitsdaten nach der DSGVO?",
        ["Sie sind besonders geschützt – nur mit starken Maßnahmen wie Verschlüsselung", "Sie gelten wie alle anderen Daten", "Sie dürfen gar nicht digital gespeichert werden"], 0,
        "Gesundheitsdaten sind eine besondere Kategorie personenbezogener Daten. Wer sie verarbeitet, muss angemessene technische Maßnahmen treffen, etwa Verschlüsselung.",
        "DSGVO Art. 9 (besondere Kategorien) und Art. 32 (Sicherheit der Verarbeitung)"),
      K(3, "Freitag, 16 Uhr",
        "Stromausfall in der ganzen Straße, Freitagnachmittag. Als der Strom zurück ist, will jeder zuerst „sein“ Gerät. Der Drucker piept, das Telefon klingelt, Dr. Müller ruft nach der Patientenakte. Frau Krämer: „Wir brauchen einen Plan. Einen echten.“",
        "„Was braucht die Praxis zuerst – den Drucker oder die Patientenakte?“",
        "Was beschreibt ein Notfallplan?",
        ["Welche Farbe die Kabel haben", "Wer was in welcher Reihenfolge wieder in Betrieb nimmt", "Wie man die Firewall abschaltet, damit alles schneller geht"], 1,
        "Ein Notfallplan legt fest, welche Prozesse zuerst wieder laufen müssen, wer zuständig ist und in welcher Reihenfolge Systeme wiederhergestellt werden.",
        "BSI-Standard 200-4 (Business Continuity Management)"),
    ],
    autohaus: [
      K(1, "Der Seniorchef",
        "Timo Brenners Vater misstraut allem, was „Cloud“ heißt. „Früher hatten wir einen Ordner. Jetzt haben wir zwei Standorte und keiner findet was.“ Gestern kam die Werkstatt nicht an die Aufträge, obwohl „die Leitung grün“ war.",
        "„Kommt die Antwort auf demselben Weg zurück, auf dem die Frage hinging?“",
        "Warum braucht auch der Router auf der anderen Seite eine Route?",
        ["Damit er schneller startet", "Weil sonst DNS nicht funktioniert", "Weil die Antwort sonst den Rückweg nicht findet"], 2,
        "Routing gilt pro Richtung: Ein Paket kann ankommen, aber die Antwort geht verloren, wenn der Router dort das Absendernetz nicht kennt.",
        "RFC 1812 (Requirements for IPv4 Routers) · Network – Lernfassung"),
      K(2, "Fernwartung für alle",
        "Timo will, dass der Hersteller des Diagnosegeräts „mal eben“ von außen draufkommt. „Der sagt, wir sollen Port 3389 aufmachen. Das ist doch nur Remote Desktop.“ Der Hersteller hat das Passwort per Mail geschickt.",
        "„Welche Tür steht jetzt für die ganze Welt offen – und wer klopft da nachts?“",
        "Warum ist ein aus dem Internet erreichbares Remote Desktop gefährlich?",
        ["Angreifer probieren dort automatisiert Passwörter und Lücken aus", "Remote Desktop funktioniert nur im LAN", "Es macht den Webshop langsamer"], 0,
        "Offen erreichbare Fernzugänge werden ständig automatisiert angegriffen. Fernwartung gehört hinter ein VPN mit starker Anmeldung und wird nur bei Bedarf freigeschaltet.",
        "BSI IT-Grundschutz-Kompendium, OPS.1.2.5 Fernwartung"),
      K(3, "Die alte Liste",
        "Der Seniorchef geht in Rente und übergibt Timo feierlich eine Excel-Liste: „Alle IP-Adressen. Hab ich selbst gepflegt.“ Stand: vor fünf Jahren. Die Hälfte der Geräte gibt es nicht mehr, drei Adressen sind doppelt vergeben.",
        "„Wem glaubst du – der Liste oder dem Netz?“",
        "Warum pflegt man Adressen zentral und gleicht sie mit dem Netz ab?",
        ["Damit das Internet schneller wird", "Damit nichts doppelt vergeben wird und die Doku stimmt", "Damit DHCP überflüssig wird"], 1,
        "Eine aktuelle Netzdokumentation verhindert doppelte Adressen und spart bei jeder Störung Zeit – aber nur, wenn sie regelmäßig mit dem echten Netz abgeglichen wird.",
        "BSI IT-Grundschutz-Kompendium, NET.1.1 Netzarchitektur und -design (Netzdokumentation)"),
    ],
    mittelstand: [
      K(1, "Der große Kunde",
        "Ein Autohersteller will Kessler als Zulieferer – und verlangt Nachweise zur Informationssicherheit. Dr. Kessler legt dir die Firewall-Regeln hin: „Bitte zu jeder Regel ein Satz, warum es sie gibt.“ Bei Regel 14 steht nur: „Test – nicht löschen“.",
        "„Kannst du jede Regel in einem Satz begründen? Wenn nicht – wofür ist sie dann da?“",
        "Warum steht am Ende einer Firewall-Regelliste „alles verbieten“?",
        ["Was nicht ausdrücklich erlaubt ist, ist verboten", "Damit die Firewall schneller arbeitet", "Weil sonst das Internet nicht funktioniert"], 0,
        "Eine Firewall arbeitet nach dem Grundsatz „Default Deny“: Nur ausdrücklich erlaubter Verkehr darf passieren, der Rest wird verworfen.",
        "BSI IT-Grundschutz-Kompendium, NET.3.2 Firewall"),
      K(2, "Der Test-Klick",
        "Dr. Kessler hat eine Phishing-Übung beauftragt. Ergebnis: Ihr eigener Assistent hat geklickt – und sein Passwort eingegeben. Sie ist nicht wütend, nur sehr ruhig: „Was hätte das gekostet, wenn es echt gewesen wäre?“",
        "„Ist das ein Fehler des Menschen – oder des Ablaufs, der ein einziges Passwort reichen lässt?“",
        "Was hilft am meisten, wenn ein Passwort gestohlen wird?",
        ["Passwörter monatlich auf einem Zettel notieren", "Mehr-Faktor-Authentisierung", "Längere Netzwerkkabel"], 1,
        "Mit Mehr-Faktor-Authentisierung reicht ein gestohlenes Passwort allein nicht – es fehlt der zweite Faktor, etwa eine App oder ein Sicherheitsschlüssel.",
        "BSI IT-Grundschutz-Kompendium, ORP.4 (Mehr-Faktor-Authentisierung)"),
      K(3, "Wer war es?",
        "Nach einem merkwürdigen Zugriff auf den Webshop fragt Dr. Kessler: „Wer war um 3:12 Uhr auf dem Server?“ Die Logs des Servers reichen 24 Stunden zurück, die der Firewall gehen eine Stunde nach. Ihr merkt es, als die Zeiten nicht zusammenpassen.",
        "„Was willst du in drei Monaten noch nachweisen können?“",
        "Warum sammelt man Protokolle zentral und mit synchroner Uhrzeit?",
        ["Damit Router schneller starten", "Damit DHCP funktioniert", "Damit Ereignisse verschiedener Geräte zusammenpassen und erhalten bleiben"], 2,
        "Protokolle sind nur auswertbar, wenn sie lange genug aufbewahrt werden und alle Geräte dieselbe Zeit haben (NTP). Zentral gesammelt gehen sie auch dann nicht verloren, wenn ein Gerät überschreibt.",
        "BSI IT-Grundschutz-Kompendium, OPS.1.1.5 Protokollierung"),
    ],
    storage: [
      K(1, "Die großen Pläne",
        "Bei Planwerk dauert das Speichern einer CAD-Datei zwei Minuten. „Das NAS ist zu langsam“, sagt Jana Wolff, „wir brauchen ein neues.“ Du schaust: Der Arbeitsplatz hängt im WLAN, das NAS am Gigabit-Switch.",
        "„Wo ist der Engpass – im Speicher oder auf dem Weg dorthin?“",
        "Warum ist eine große Datei über Gigabit-Kabel schneller gespeichert als über WLAN?",
        ["Kabel komprimiert die Daten", "WLAN ist ein geteiltes Funkmedium und liefert real deutlich weniger als den Nennwert", "Über WLAN wird nicht verschlüsselt"], 1,
        "WLAN teilen sich alle Geräte einer Funkzelle; sie senden abwechselnd, und die Nutzrate liegt deutlich unter der beworbenen Bruttorate. Gigabit-Ethernet am Switch ist vollduplex und exklusiv.",
        "IEEE 802.11 (Medienzugriff CSMA/CA) · IEEE 802.3ab (1000BASE-T)"),
      K(2, "Freitag, 18 Uhr",
        "Ein Mitarbeiter hat einen Mail-Anhang geöffnet; ein Projektordner ist verschlüsselt. Jana ist blass. Dann zeigst du ihr den Snapshot von heute Mittag auf dem NAS – zwei Klicks, und der Ordner ist wieder da. Sie atmet aus: „Und wenn das NAS selbst kaputtgeht?“",
        "„Gute Frage. Wo liegt der Snapshot – und wo das NAS?“",
        "Was unterscheidet einen Snapshot von einer Sicherung?",
        ["Der Snapshot liegt auf demselben System, eine Sicherung auf einem anderen", "Es gibt keinen Unterschied", "Snapshots sind immer verschlüsselt"], 0,
        "Ein Snapshot hält einen Stand auf demselben Speicher fest – praktisch gegen Löschen und Verschlüsseln, aber wertlos, wenn das System selbst ausfällt. Eine Sicherung liegt getrennt davon.",
        "SNIA Dictionary („Snapshot“) · BSI IT-Grundschutz-Kompendium, CON.3 Datensicherungskonzept"),
      K(3, "Cloud oder Keller?",
        "Jana überlegt, alles in die Cloud zu legen: vier Terabyte Projekte. „Der Anbieter sagt, das geht übers Wochenende.“ Ihr Internetanschluss lädt mit 50 Megabit pro Sekunde hoch.",
        "„Rechne nach, bevor du etwas versprichst.“",
        "Wie lange dauert es ungefähr, 4 TB mit 50 Mbit/s hochzuladen?",
        ["Etwa eine Stunde", "Etwa ein Jahr", "Etwa eine Woche"], 2,
        "4 TB = 4 · 10¹² Byte = 3,2 · 10¹³ Bit. Geteilt durch 5 · 10⁷ Bit/s sind das 640 000 Sekunden – rund 7,4 Tage, ohne Pausen und Protokoll-Overhead.",
        "Eigene Rechnung (Datenmenge × 8 ÷ Datenrate)"),
    ],
  };
})();
