"use strict";
/* ---------- Lehrtexte zu den Gründen der Simulation (Architektur § 5.3) ----------
   DATEN.lehrtexte[code] = {titel, E, AP1, AP2, quelle, skill}
   E    Einstieg: was passiert, warum, woran man es erkennt, was man als Nächstes prüft (2–4 Sätze)
   AP1  fachlich knapp (1–2 Sätze)
   AP2  nur, was Gerät oder Werkzeug selbst melden würde (Windows-Meldungen deutsch, IOS englisch, gekürzt mit …)
   quelle  Vault-Notiz und/oder RFC bzw. Hersteller-Doku. skill = Fertigkeit aus DATEN.skills.
   Reine Daten, keine Logik. */
Object.assign(DATEN.lehrtexte, {
  LINK_DOWN: {
    titel: "Kein Link",
    skill: "lab.link",
    E: "Auf dieser Leitung kommt kein Signal an: Das Kabel fehlt, steckt im falschen Port oder die Gegenstelle ist aus. Ohne Link (Schicht 1) geht kein einziger Frame durch, egal wie gut IP-Adresse und Gateway eingestellt sind. Du erkennst es an der roten Leitung und am Status „down“. Prüf als Nächstes, ob beide Enden stecken und beide Geräte eingeschaltet sind.",
    AP1: "Schicht-1-Fehler: Die Schnittstelle steht auf down/down, weil Kabel oder Gegenstelle fehlen. Erst den Link herstellen, dann die höheren Schichten prüfen.",
    AP2: "show ip interface brief: Status down, Protocol down · Windows ipconfig: „Medienstatus: Medium getrennt“",
    quelle: "Fragen – Netzwerke planen (Fehlersuche nach OSI von unten) · Cisco IOS Interface Command Reference (show ip interface brief)",
  },
  PORT_SHUTDOWN: {
    titel: "Schnittstelle abgeschaltet",
    skill: "lab.link",
    E: "Die Schnittstelle ist per Befehl abgeschaltet (shutdown). Das Kabel steckt, aber der Port sendet und empfängt nichts. Router-Schnittstellen sind ab Werk abgeschaltet, Switchports dagegen eingeschaltet. Schalte die Schnittstelle im Inspektor ein oder tippe in ihrer Konfiguration „no shutdown“.",
    AP1: "Die Schnittstelle ist administrativ abgeschaltet (Status „administratively down“). Abhilfe: no shutdown in der Schnittstellenkonfiguration.",
    AP2: "show ip interface brief: administratively down   down",
    quelle: "Cisco IOS Interface Command Reference (shutdown) · Fragen – Netzwerke planen (Fehlersuche)",
  },
  NO_IP: {
    titel: "Keine IP-Adresse",
    skill: "lab.ip",
    E: "Dieses Gerät hat auf der Schnittstelle keine IP-Adresse. Ohne eigene Adresse kann es kein IP-Paket absenden, und niemand kann ihm antworten. Trag eine freie Adresse aus dem richtigen Netz samt Subnetzmaske ein oder schalte DHCP ein.",
    AP1: "Schnittstelle ohne IPv4-Adresse, damit ist kein IP-Verkehr möglich. Adresse und Maske statisch setzen oder per DHCP beziehen.",
    AP2: "show ip interface brief: IP-Address unassigned · Windows ipconfig: keine Zeile „IPv4-Adresse“",
    quelle: "Network – Lernfassung (§ 7 IPv4-Adressen) · Cisco IOS IP Addressing Command Reference (ip address)",
  },
  ARP_NO_REPLY: {
    titel: "Keine ARP-Antwort",
    skill: "lab.arp",
    E: "Der Absender hat im eigenen Netz gerufen „Wer hat diese IP-Adresse?“, aber niemand hat geantwortet. Ohne MAC-Adresse kann er den Frame nicht adressieren, das Paket bleibt liegen. Meist ist die Ziel-IP falsch, das Ziel aus, in einem anderen VLAN, oder die Maske täuscht ein gemeinsames Netz nur vor. Prüf, ob es ein Gerät mit genau dieser IP im selben VLAN gibt.",
    AP1: "Der ARP-Request (Broadcast) bleibt unbeantwortet, die Ziel-IP lässt sich nicht in eine MAC auflösen. Ursachen: Ziel fehlt oder ist aus, falsche IP oder Maske, anderes VLAN.",
    AP2: "Windows: Antwort von der eigenen Adresse: „Zielhost nicht erreichbar.“ · IOS show ip arp: „Incomplete“",
    quelle: "Network – Lernfassung (§ 9 ARP Schritt für Schritt) · RFC 826",
  },
  DROP_VLAN: {
    titel: "Anderes VLAN",
    skill: "lab.vlan",
    E: "Der Switch hat den Frame nicht zugestellt, weil Absender und Ziel in verschiedenen VLANs stecken. Ein VLAN verhält sich wie ein eigener Switch im selben Gehäuse: Frames wechseln nie von selbst in ein anderes VLAN. Schau im Inspektor des Switches nach, in welchem VLAN die beiden Ports sind. Sollen die Geräte sich direkt erreichen, gehören sie ins selbe VLAN, sonst braucht es einen Router.",
    AP1: "Quell- und Zielport liegen in verschiedenen VLANs, also in verschiedenen Broadcast-Domänen. Zwischen VLANs vermittelt nur ein Router oder Layer-3-Switch.",
    AP2: "Keine Meldung, der Switch leitet still nicht weiter · Am Absender: „Zielhost nicht erreichbar.“",
    quelle: "VLAN – Lernfassung · VLAN – Visuelle Lernnotiz (§ 7 Zwischen VLANs routen) · IEEE 802.1Q",
  },
  TRUNK_NOT_ALLOWED: {
    titel: "VLAN auf dem Trunk nicht erlaubt",
    skill: "lab.trunk",
    E: "Der Frame gehört zu einem VLAN, das auf diesem Trunk nicht in der Liste der erlaubten VLANs steht. Der Switch schickt ihn deshalb nicht über die Verbindung, und auf der anderen Seite kommt nichts an. Typische Falle: „switchport trunk allowed vlan 30“ ohne „add“ ersetzt die ganze Liste. Prüf mit „show interfaces trunk“, welche VLANs erlaubt sind.",
    AP1: "Das VLAN fehlt in der Allowed-Liste des Trunks und wird nicht übertragen. Mit switchport trunk allowed vlan add ergänzen.",
    AP2: "Keine Meldung · show interfaces trunk: VLAN fehlt unter „Vlans allowed on trunk“",
    quelle: "VLAN – Lernfassung (§ 2 Befehle) · Cisco Catalyst Software Configuration Guide: Configuring VLAN Trunks",
  },
  NATIVE_MISMATCH: {
    titel: "Native VLAN ungleich",
    skill: "lab.trunk",
    E: "Die beiden Enden des Trunks haben verschiedene Native VLANs eingestellt. Frames ohne Tag landen dadurch auf der anderen Seite im falschen VLAN, zwei VLANs laufen ineinander. Stell das Native VLAN auf beiden Seiten gleich ein, am besten auf ein VLAN, das sonst niemand benutzt.",
    AP1: "Native-VLAN-Mismatch: Ungetaggte Frames werden auf der Gegenseite einem anderen VLAN zugeordnet. Native VLAN auf beiden Trunk-Enden gleich setzen.",
    AP2: "%CDP-4-NATIVE_VLAN_MISMATCH: Native VLAN mismatch discovered on …",
    quelle: "VLAN – Lernfassung (§ 2 Kleingedrucktes) · VLAN – Visuelle Lernnotiz (§ 8 VLAN 1) · IEEE 802.1Q",
  },
  NO_GATEWAY: {
    titel: "Kein Standardgateway",
    skill: "lab.gateway",
    E: "Das Ziel liegt in einem anderen Netz, aber beim Absender ist kein Standardgateway eingetragen. Der Rechner weiß nicht, wem er Pakete für fremde Netze geben soll, und schickt sie gar nicht erst los. Im eigenen Netz klappt alles, nach draußen nichts. Trag als Gateway die Adresse des Routers in deinem Netz ein.",
    AP1: "Ziel außerhalb des eigenen Subnetzes, aber kein Default Gateway konfiguriert: Das Paket kann nicht zugestellt werden.",
    AP2: "ipconfig: „Standardgateway“ ohne Eintrag · ping: „PING: Fehler bei der Übertragung. Allgemeiner Fehler.“",
    quelle: "Network – Lernfassung (§ 0 Landkarte, § 9) · Netzwerk – Geschichten („Die Straße, in der Lappi wohnt“)",
  },
  GW_WRONG_SUBNET: {
    titel: "Gateway im falschen Netz",
    skill: "lab.gateway",
    E: "Das eingetragene Gateway liegt nicht im eigenen Netz des Rechners. Ein Gateway muss aber direkt erreichbar sein, also im selben Subnetz wie die eigene Adresse. Meist ist die Adresse vertippt oder die Maske passt nicht. Rechne die Netz-ID von eigener IP und Gateway mit derselben Maske aus und vergleiche.",
    AP1: "Das Default Gateway liegt außerhalb des eigenen Subnetzes und ist damit nicht direkt erreichbar. Es muss im Netz aus eigener IP und Maske liegen.",
    AP2: "Windows warnt beim Speichern: Standardgateway nicht im selben Netzwerksegment (Subnetz)",
    quelle: "Network – Lernfassung (§ 8 Subnetting, § 9 Gateway) · 04-AP1-Netzwerk",
  },
  GW_UNREACHABLE: {
    titel: "Gateway antwortet nicht",
    skill: "lab.gateway",
    E: "Das Gateway steht im richtigen Netz, antwortet aber nicht auf die ARP-Anfrage. Entweder gibt es unter dieser Adresse keinen Router, seine Schnittstelle ist abgeschaltet, oder das Kabel zum Router fehlt. Ping zuerst das Gateway selbst an und prüf dann die Router-Schnittstelle.",
    AP1: "Das Default Gateway liegt im eigenen Netz, ist aber nicht erreichbar (keine ARP-Antwort). Ursachen: falsche Gateway-Adresse, Router-Schnittstelle down oder kein Link.",
    AP2: "Windows: Antwort von der eigenen Adresse: „Zielhost nicht erreichbar.“ · arp -a: kein Eintrag für das Gateway",
    quelle: "Network – Lernfassung (§ 9: Liegt das Ziel in einem anderen Netz?)",
  },
  WRONG_MASK: {
    titel: "Falsche Subnetzmaske",
    skill: "lab.netz",
    E: "Die Subnetzmaske passt nicht zum Netz. Dadurch hält der Rechner fremde Adressen für lokal oder lokale für fremd: Er sucht Geräte hinter dem Router per ARP im eigenen Netz, oder er schickt Nachbarn unnötig zum Gateway. Vergleich die Maske mit den anderen Geräten im selben Netz, meist ist nur eine Zahl vertippt.",
    AP1: "Eine falsche Maske führt zur falschen Entscheidung zwischen direkt und Gateway: Ziele werden fälschlich per ARP im eigenen Netz gesucht oder unnötig ans Gateway gesendet.",
    AP2: "Keine Meldung vom Gerät · einzelne Ziele: „Zielhost nicht erreichbar.“",
    quelle: "Network – Lernfassung (§ 8 Subnetting) · 04-AP1-Netzwerk (Subnetting-Verfahren)",
  },
  NO_ROUTE: {
    titel: "Keine Route",
    skill: "lab.route",
    E: "Ein Router hat in seiner Routingtabelle keinen Eintrag für das Zielnetz und auch keine Default-Route. Er verwirft das Paket und schickt dem Absender die Meldung „Zielnetz nicht erreichbar“ zurück. Anders als bei einer Zeitüberschreitung meldet sich hier jemand, und seine Adresse verrät dir, wo es hängt. Prüf mit „show ip route“, welche Netze der Router kennt, und ergänze eine statische Route oder eine Default-Route.",
    AP1: "Keine passende Route und keine Default-Route: Der Router verwirft das Paket und sendet ICMP Destination Unreachable (Netz nicht erreichbar).",
    AP2: "Windows: Antwort vom Router: „Zielnetz nicht erreichbar.“ · IOS ping: U.U.U",
    quelle: "RFC 792 (Destination Unreachable) · Cisco: Understanding the Ping and Traceroute Commands · Fragen – Netzwerke planen (Routing)",
  },
  NO_RETURN_ROUTE: {
    titel: "Keine Rückroute",
    skill: "lab.route",
    E: "Das Paket ist beim Ziel angekommen, aber die Antwort findet den Weg zurück nicht: Ein Router auf dem Rückweg kennt das Netz des Absenders nicht. Für den Absender sieht das aus wie ein stummes Ziel, er bekommt nur eine Zeitüberschreitung. Routen gelten immer nur in eine Richtung, also prüf die Routingtabellen auf dem Rückweg.",
    AP1: "Hinweg geroutet, Rückweg fehlt: Die Antwort wird unterwegs verworfen. Symptom beim Sender ist ein Timeout, kein Unreachable.",
    AP2: "Windows: „Zeitüberschreitung der Anforderung.“ · IOS ping: .....",
    quelle: "Network – Lernfassung (§ 0: die Antwort braucht ebenfalls einen Weg) · Cisco IOS IP Routing: Static Routing Configuration Guide",
  },
  TTL_EXPIRED: {
    titel: "TTL abgelaufen",
    skill: "lab.ttl",
    E: "Jeder Router zieht von der TTL (Time To Live) eines Pakets 1 ab. Erreicht sie 0, wird das Paket verworfen, und der Absender bekommt die Meldung „TTL abgelaufen“. Passiert das bei einem normalen Ping, kreist das Paket meist zwischen zwei Routern, die sich gegenseitig als Weg eingetragen haben. Mit Traceroute siehst du, wo es im Kreis geht.",
    AP1: "Die TTL erreicht 0, das Paket wird verworfen und ICMP Time Exceeded geht an den Absender. Häufige Ursache ist eine Routingschleife.",
    AP2: "Windows: „Die Gültigkeitsdauer wurde bei der Übertragung überschritten.“ · IOS ping: &",
    quelle: "Network – Lernfassung (§ 5, § 10 tracert) · RFC 791 · RFC 792 (Time Exceeded)",
  },
  ACL_DENY: {
    titel: "Von ACL verworfen",
    skill: "lab.acl",
    E: "Eine Access-Liste am Router hat das Paket verworfen. Der Router prüft die Regeln von oben nach unten, die erste passende entscheidet, und am Ende steht unsichtbar „alles andere verbieten“. Oft steht eine zu allgemeine deny-Regel vor der gewünschten permit-Regel, oder das permit fehlt ganz. Schau mit „show access-lists“ nach, welche Regel Treffer zählt.",
    AP1: "Die erste passende Regel ist deny, oder keine Regel passt (implizites deny any am Ende). Reihenfolge der Regeln und Richtung (in/out) prüfen.",
    AP2: "IOS ping: U.U.U · show access-lists: Trefferzähler „(… matches)“ an der deny-Regel",
    quelle: "Cisco IOS Security Configuration Guide: IP Access Lists · Infrastruktur & Sicherheit – Visuelle Lernnotiz (Firewall: Reihenfolge der Regeln)",
  },
  FW_DENY: {
    titel: "Firewall-Regel verwirft",
    skill: "lab.fw",
    E: "Die Firewall hat keine Regel gefunden, die diesen Verkehr erlaubt, oder eine Regel verbietet ihn ausdrücklich. Sie arbeitet ihre Regeln von oben nach unten ab und verwirft am Ende alles, was nicht erlaubt ist. Antworten auf erlaubte Verbindungen lässt sie automatisch zurück. Prüf bei der Regel Richtung (von Zone, nach Zone), Protokoll und Port.",
    AP1: "Der Verkehr ist durch das Regelwerk nicht erlaubt (deny by default) oder wird ausdrücklich verworfen. Rückverkehr erlaubter Verbindungen passiert automatisch (zustandsbehaftet).",
    AP2: "Windows: „Zeitüberschreitung der Anforderung.“ · Firewall-Protokoll: Verbindung verworfen",
    quelle: "05-AP2-Infrastruktur-Sicherheit (Firewall-Grundregeln) · Infrastruktur & Sicherheit – Visuelle Lernnotiz (Firewall)",
  },
  NAT_MISSING: {
    titel: "NAT fehlt",
    skill: "lab.nat",
    E: "Ein Paket mit privater Absenderadresse wie 192.168.1.10 will ins Internet. Private Adressen werden dort nicht geroutet, deshalb muss der Router sie vorher durch seine öffentliche Adresse ersetzen (NAT). Hier passiert das nicht: NAT fehlt, die Access-Liste erfasst das Netz nicht, oder inside und outside sind vertauscht. Prüf „ip nat inside“ an der LAN-Schnittstelle und „ip nat outside“ an der Internet-Schnittstelle.",
    AP1: "Eine private Quelladresse (RFC 1918) gelangt unübersetzt ins Internet und wird verworfen. NAT/PAT konfigurieren bzw. inside und outside richtig zuordnen.",
    AP2: "Windows: „Zeitüberschreitung der Anforderung.“ · show ip nat translations: keine Einträge",
    quelle: "Network – Lernfassung (§ 7, Korrektur 14) · RFC 1918 · RFC 3022 · Cisco IOS NAT Configuration Guide",
  },
  DUP_IP: {
    titel: "Adresskonflikt",
    skill: "lab.ip",
    E: "Zwei Geräte benutzen dieselbe IP-Adresse. Wer die Adresse anspricht, landet mal beim einen, mal beim anderen Gerät, je nachdem, wer zuletzt per ARP geantwortet hat. Das wirkt wie ein Wackelkontakt. Gib jedem Gerät eine eigene Adresse und trag feste Adressen in den Adressplan ein.",
    AP1: "Doppelte IP im Subnetz: Der ARP-Eintrag wechselt zwischen zwei MAC-Adressen, Verbindungen brechen sporadisch ab.",
    AP2: "IOS: %IP-4-DUPADDR: Duplicate address … sourced by … · Windows meldet einen IP-Adresskonflikt",
    quelle: "Network – Lernfassung (§ 9 ARP) · RFC 5227 (IPv4 Address Conflict Detection)",
  },
  DHCP_NO_OFFER: {
    titel: "Kein DHCP-Angebot",
    skill: "lab.dhcp",
    E: "Der Rechner hat per Broadcast nach einem DHCP-Server gerufen (Discover), aber kein Angebot bekommen. Deshalb gibt er sich selbst eine Notadresse aus 169.254.x.x (APIPA), mit der er nur Nachbarn mit ebensolcher Adresse erreicht. Broadcasts gehen nicht über Router: Steht der DHCP-Server in einem anderen Netz oder VLAN, braucht der Router „ip helper-address“. Prüf außerdem Kabel, VLAN und ob der DHCP-Dienst läuft.",
    AP1: "Der DHCP-Discover bleibt unbeantwortet, der Client vergibt sich eine APIPA-Adresse aus 169.254.0.0/16. Ursachen: Server aus, falsches VLAN oder fehlendes Relay (ip helper-address).",
    AP2: "ipconfig /all: „Autokonfiguration IPv4-Adresse: 169.254.…“",
    quelle: "Network – Lernfassung (§ 7 Besondere Adressen, § 9 DORA) · RFC 2131 · RFC 3927",
  },
  DHCP_POOL_EMPTY: {
    titel: "DHCP-Pool erschöpft",
    skill: "lab.dhcp",
    E: "Der DHCP-Server läuft, hat aber keine freie Adresse mehr: Alle Adressen seines Pools sind verliehen. Er schickt deshalb kein Angebot, und der neue Rechner nimmt eine Notadresse aus 169.254.x.x. Vergrößere den Pool, gib nicht mehr benötigte Leases frei oder verkleinere ausgeschlossene Bereiche, die niemand braucht.",
    AP1: "Der Adresspool ist erschöpft: Der Server sendet kein Offer, der Client fällt auf APIPA zurück. Pool vergrößern oder Leases prüfen.",
    AP2: "Client: „Autokonfiguration IPv4-Adresse: 169.254.…“ · show ip dhcp binding: alle Adressen des Pools vergeben",
    quelle: "Network – Lernfassung (§ 9 DHCP) · RFC 2131 · Cisco IOS DHCP Server Configuration Guide",
  },
  DHCP_LEASE_EXPIRED: {
    titel: "DHCP-Lease abgelaufen",
    skill: "lab.dhcp",
    E: "Eine per DHCP bezogene Adresse gilt nur für eine bestimmte Zeit (Lease-Time). Ist sie abgelaufen, darf der Rechner sie nicht weiter benutzen: Er hat keine gültige Adresse mehr und muss sie neu beantragen. Deshalb steht in der Anzeige „keine Adresse“, obwohl vorher alles lief. In der Praxis fällt das selten auf, weil der Client rechtzeitig verlängert – bei der Hälfte der Lease-Time (T1) fragt er beim selben Server um Verlängerung.",
    AP1: "Die Lease ist abgelaufen (Zeit > Ablaufzeitpunkt). Die Adresse gilt nicht mehr, der Client bezieht per DORA eine neue. Verlängert wird normalerweise bei 50 % der Lease-Time (T1), danach sucht der Client bei jedem Server (Rebind, T2).",
    AP2: "ipconfig /all: „Lease erhalten/abläuft“ · show ip dhcp binding: Zustand abgelaufen",
    quelle: "RFC 2131 (§ 4.4.5 Lease-Parameter, T1/T2) · RFC 2132 (Option 51 Lease Time, Option 58/59 T1/T2)",
  },
  DHCP_RESERVED_BUSY: {
    titel: "Reservierte Adresse belegt",
    skill: "lab.dhcp",
    E: "Für dieses Gerät ist eine feste Adresse reserviert – der Server erkennt es an seiner MAC-Adresse. Diese Adresse ist aber gerade schon vergeben, zum Beispiel weil sie zusätzlich fest in einem anderen Gerät eingetragen wurde. Der Server vergibt die reservierte Adresse dann nicht, und das Gerät bekommt kein Angebot. Prüf, ob die reservierte Adresse außerhalb des freien Bereichs liegt und nirgends statisch eingetragen ist.",
    AP1: "Die Reservierung (MAC → IP) zeigt auf eine bereits belegte Adresse. Der Server lehnt ab, das Gerät erhält keine Adresse. Reservierte Adressen gehören außerhalb des DHCP-Bereichs oder müssen dort ausgeschlossen werden.",
    AP2: "show ip dhcp binding: Adresse einem anderen Eintrag zugeordnet · show ip dhcp conflict",
    quelle: "RFC 2131 (§ 4.3.1, „manual allocation“) · RFC 2132 (Option 50 Requested IP Address)",
  },
  DHCP_ROGUE_OFFER: {
    titel: "Angebot von fremdem DHCP-Server",
    skill: "lab.dhcp",
    E: "In diesem Netz antwortet ein zweiter DHCP-Server, der dort nicht hingehört. Er verteilt eine Adresse mit falschem Gateway oder falschem DNS-Server. Der Rechner nimmt das erste Angebot, das ankommt – ob vom richtigen oder vom falschen Server. Danach kommt er zwar ins eigene Netz, aber nicht mehr ins Internet. Finde den fremden Server (wer antwortet auf Port 67?) und schalte ihn ab oder blockiere seine Antworten am Switch (DHCP-Snooping).",
    AP1: "Ein unerlaubter DHCP-Server im selben Broadcastbereich verteilt falsche Optionen (Gateway/DNS). Der Client übernimmt das erste Angebot. Gegenmaßnahme: DHCP-Snooping mit vertrauten Ports oder den fremden Server entfernen.",
    AP2: "Symptom: gültige Adresse, aber „Standardgateway“ zeigt auf ein fremdes Gerät · ipconfig /all: DHCP-Server ist nicht der erwartete",
    quelle: "RFC 2131 · IOS-ähnlich (Snooping-Wortlaut und Anzeige sind nicht normiert)",
  },
  DHCP_SNOOPING_BLOCKED: {
    titel: "DHCP-Snooping blockiert",
    skill: "lab.dhcp",
    E: "Der Switch filtert DHCP-Antworten: Nur an „vertrauten“ Ports darf ein DHCP-Server antworten, alle anderen Ports dürfen nur Anfragen stellen. Hängt der richtige DHCP-Server an einem Port, der nicht als vertraut markiert ist, kommen seine Angebote nie beim Client an – der Rechner bekommt keine Adresse, obwohl der Server läuft. Trag den Port zum Server als vertraut ein.",
    AP1: "DHCP-Snooping verwirft Server-Antworten (Offer/Ack) an nicht vertrauten Ports. Client-Anfragen (Discover/Request) sind immer erlaubt. Der Serverport muss als vertraut konfiguriert sein.",
    AP2: "show ip dhcp snooping: Zähler verworfener Pakete je Port · IOS-ähnlich: „ip dhcp snooping trust“ am Uplink",
    quelle: "RFC 2131 · IOS-ähnlich (Snooping ist eine Switch-Funktion, kein RFC-Verfahren)",
  },
  DHCP_CONFLICT: {
    titel: "Adresskonflikt im Pool",
    skill: "lab.dhcp",
    E: "Zwei Geräte tragen dieselbe IP-Adresse. Der DHCP-Server merkt das, wenn er eine Adresse vor der Vergabe prüft, und überspringt sie. Ein Konflikt entsteht meistens dadurch, dass jemand eine Adresse fest einträgt, die im DHCP-Bereich liegt und dort schon vergeben wurde. Lösung: die feste Adresse aus dem DHCP-Bereich herausnehmen oder den Bereich verkleinern.",
    AP1: "Dieselbe IPv4-Adresse ist auf mehr als einem Gerät konfiguriert. Der Server vermerkt den Konflikt und vergibt die Adresse nicht erneut. Statische Adressen gehören außerhalb des DHCP-Bereichs.",
    AP2: "show ip dhcp conflict: Adresse mit Erkennungsmethode und Zeitpunkt · Windows meldet „Es liegt ein IP-Adresskonflikt vor“",
    quelle: "RFC 5227 (IPv4 Address Conflict Detection) · RFC 2131 · IOS-ähnlich (Anzeige)",
  },
  DNS_FAIL: {
    titel: "Name nicht auflösbar",
    skill: "lab.dns",
    E: "Der DNS-Server wurde erreicht, kennt den gesuchten Namen aber nicht. Eine Verbindung per IP-Adresse würde klappen, nur der Name führt ins Leere. Prüf den Namen auf Tippfehler und ob der Eintrag auf dem DNS-Server existiert. Guter Test: erst mit der IP-Adresse pingen, dann mit dem Namen.",
    AP1: "Die DNS-Abfrage wird beantwortet, aber es gibt keinen Eintrag für den Namen (NXDOMAIN). Ping per IP geht, per Name nicht.",
    AP2: "„Ping-Anforderung konnte Host … nicht finden. Überprüfen Sie den Namen, und versuchen Sie es erneut.“ · nslookup: „Non-existent domain“",
    quelle: "Network – Lernfassung (§ 9 DNS) · RFC 1034 · RFC 1035",
  },
  DNS_NO_SERVER: {
    titel: "Kein DNS-Server erreichbar",
    skill: "lab.dns",
    E: "Der Rechner soll einen Namen auflösen, hat aber keinen DNS-Server eingetragen, oder der eingetragene antwortet nicht. Ohne Antwort vom DNS kennt er zum Namen keine IP-Adresse. Trag die Adresse des DNS-Servers ein und prüf, ob der DNS-Dienst auf ihm läuft und ob er erreichbar ist.",
    AP1: "Kein oder ein nicht erreichbarer DNS-Server: Die Namensauflösung scheitert, Verbindungen per IP funktionieren weiter.",
    AP2: "ipconfig /all: „DNS-Server“ leer oder falsch · ping per Name: „Ping-Anforderung konnte Host … nicht finden.“",
    quelle: "Network – Lernfassung (§ 9 DNS, § 10 Werkzeugkasten)",
  },
  PORT_CLOSED: {
    titel: "Port geschlossen",
    skill: "lab.ports",
    E: "Das Ziel ist erreichbar, aber auf diesem Port lauscht kein Dienst. Der Server antwortet deshalb sofort mit einem Abbruch (TCP-RST) statt mit SYN/ACK. Ping klappt also, die Verbindung zum Dienst nicht. Prüf, ob du den richtigen Port ansprichst, zum Beispiel 443 statt 80, und ob der Dienst auf dem Server eingerichtet ist.",
    AP1: "Ein TCP-SYN auf einen geschlossenen Port wird mit RST beantwortet: Host erreichbar, Dienst nicht. Portnummer und Dienst prüfen.",
    AP2: "Verbindung abgelehnt (TCP RST) · Browser: ERR_CONNECTION_REFUSED",
    quelle: "TCP – Lernfassung (§ 5: RST bei geschlossenem Port) · RFC 9293",
  },
  SERVICE_OFF: {
    titel: "Dienst ausgeschaltet",
    skill: "lab.ports",
    E: "Der gewünschte Dienst, etwa Webserver, Dateifreigabe oder DNS, ist auf dem Zielgerät nicht eingeschaltet. Das Gerät selbst antwortet auf Ping, der Dienst aber nicht. Schalte ihn im Inspektor unter „Dienste“ ein.",
    AP1: "Ziel erreichbar, Dienst nicht aktiv: TCP-Verbindungen werden mit RST abgewiesen, UDP-Anfragen mit ICMP Port Unreachable. Dienst starten.",
    AP2: "ping zum Server: Antwort · Dienst: Verbindung abgelehnt",
    quelle: "04-AP1-Netzwerk (Ports) · VLAN – Visuelle Lernnotiz (§ 1 Port ist nicht gleich Port) · RFC 792 · RFC 9293",
  },
  STORM: {
    titel: "Broadcast-Sturm",
    skill: "lab.stp",
    E: "Im Netz gibt es eine Schleife zwischen Switches, und Spanning Tree ist nicht aktiv. Ein einziger Broadcast kreist dann endlos und vervielfacht sich an jedem Switch, denn Ethernet-Frames haben keine TTL. Die Simulation hat deshalb abgebrochen. Entferne die doppelte Verbindung oder lass Spanning Tree einen der Wege blockieren.",
    AP1: "Layer-2-Schleife ohne STP: Broadcasts zirkulieren unbegrenzt, weil Schicht 2 keine TTL kennt, und das Netz ist überlastet. Redundante Wege nur mit STP.",
    AP2: "%SW_MATM-4-MACFLAP_NOTIF: Host … is flapping between port … and port …",
    quelle: "Fragen – Netzwerke planen (Wozu STP?) · IEEE 802.1D",
  },
  PORTSEC_VIOLATION: {
    titel: "Port-Security-Verstoß",
    skill: "lab.portsec",
    E: "An diesem Switchport ist Port-Security aktiv, und ein Gerät mit nicht erlaubter MAC-Adresse hat gesendet. In der Standardeinstellung schaltet der Switch den Port dann ab (err-disabled), bis ihn jemand wieder freigibt. Prüf, ob das richtige Gerät angeschlossen ist, pass die erlaubten MACs an und schalte den Port mit „shutdown“ und danach „no shutdown“ wieder ein.",
    AP1: "Unbekannte Quell-MAC am gesicherten Port: Die Standardaktion shutdown versetzt den Port in den Zustand err-disabled. Zulässige MACs prüfen, Port neu aktivieren.",
    AP2: "%PORT_SECURITY-2-PSECURE_VIOLATION: Security violation occurred, caused by MAC address … on port …",
    quelle: "Cisco Catalyst Software Configuration Guide: Configuring Port Security · Network – Lernfassung (§ 9 MAC Flooding, Abwehr Port Security)",
  },
  DEVICE_OFF: {
    titel: "Gerät ausgeschaltet",
    skill: "lab.link",
    E: "Das Gerät ist ausgeschaltet. Alle seine Leitungen sind ohne Link, und es antwortet auf nichts. Schalte es im Inspektor ein und prüf danach, ob seine Leitungen wieder grün sind.",
    AP1: "Gerät ohne Strom: Alle Schnittstellen sind ohne Link, es kommt keine Antwort. Gerät einschalten.",
    AP2: "Gegenstelle: Status down · Ping bleibt ohne Antwort",
    quelle: "Fragen – Netzwerke planen (Fehlersuche nach OSI von unten)",
  },
  HOST_UNREACHABLE: {
    titel: "Zielhost nicht erreichbar",
    skill: "lab.ping",
    E: "Ein Gerät unterwegs meldet ausdrücklich, dass es das Ziel nicht erreicht. Das ist eine hilfreiche Nachricht, denn sie sagt dir, wer aufgegeben hat. Kommt sie von deinem eigenen Rechner, hat die ARP-Anfrage im eigenen Netz keine Antwort bekommen, kommt sie von einem Router, konnte er das Paket nicht weiter zustellen. Schau also zuerst, welche Adresse hinter „Antwort von“ steht.",
    AP1: "ICMP Destination Unreachable: Ein Gerät auf dem Weg kann das Paket nicht zustellen und meldet das. Die Absenderadresse der Meldung zeigt, wo es hakt.",
    AP2: "Windows: „Antwort von …: Zielhost nicht erreichbar.“ · IOS ping: U",
    quelle: "RFC 792 (Destination Unreachable) · Cisco: Understanding the Ping and Traceroute Commands",
  },
  TIMEOUT: {
    titel: "Zeitüberschreitung",
    skill: "lab.ping",
    E: "Auf die Anfrage kam innerhalb der Wartezeit keine Antwort, und niemand hat einen Fehler gemeldet. Irgendwo auf dem Hin- oder Rückweg wurde still verworfen, etwa durch eine Firewall, eine fehlende Rückroute oder fehlendes NAT. Anders als „nicht erreichbar“ verrät dir ein Timeout nicht, wo es hängt. Grenz die Stelle mit Traceroute oder der Simulation ein.",
    AP1: "Keine Antwort innerhalb des Timeouts (Windows 4 s, IOS 2 s): Das Paket wurde still verworfen, der Ort ist unbekannt. Eingrenzen mit traceroute oder Simulation.",
    AP2: "Windows: „Zeitüberschreitung der Anforderung.“ · IOS ping: .....",
    quelle: "Cisco: Understanding the Ping and Traceroute Commands · Microsoft Learn: ping · Network – Lernfassung (§ 10 Werkzeugkasten)",
  },
});
